server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/fluke/Documents/SOP/SOP_LAB/configurationlab/src/main/resources/config/microservice
